codecov:
  branch: main
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      default:
        target: 75
        threshold: 1
        base: auto
    patch:
      default:
        target: 80
        threshold: 1
        base: auto

github_checks:
  annotations: true

parsers:
  jacoco:
    partials_as_hits: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

fixes:
  - ":::"

ignore:
  - "rulify-example.*"
  - "coverage"
  - ".*\\.generated\\..*"
  - ".*\\.g\\..*"
  - ".*Lombok.*"
  - ".*Config.*"
