title: Rulify documentation
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
remote_theme: just-the-docs/just-the-docs
url: https://faltfe.github.io/rulify # the base hostname & protocol for your site, e.g. http://example.com

github_username: faltfe

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

aux_links:
  "Repository":
    - "https://github.com/faltfe/rulify"
  "Open an issues":
    - "https://github.com/faltfe/rulify/issues"

aux_links_new_tab: true

heading_anchors: true

# Footer
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/faltfe/rulify"
gh_edit_branch: "gh-pages"
gh_edit_view_mode: "tree"